parameters:
    oro_form.autocomplete.search_registry.class: Oro\Bundle\FormBundle\Autocomplete\SearchRegistry
    oro_form.autocomplete.search_handler.class:  Oro\Bundle\FormBundle\Autocomplete\SearchHandler

services:
    oro_form.autocomplete.search_registry:
        class: %oro_form.autocomplete.search_registry.class%

    oro_form.autocomplete.search_handler:
        class: %oro_form.autocomplete.search_handler.class%
        abstract: true
        calls:
            - [initSearchIndexer, ["@oro_search.index", %oro_search.entities_config%]]
            - [setManagerRegistry, ["@doctrine"]]
