parameters:
    oro_form.type.date.class:              Oro\Bundle\FormBundle\Form\Type\OroDateType
    oro_form.type.datetime.class:          Oro\Bundle\FormBundle\Form\Type\OroDateTimeType
    oro_form.type.combobox_local.class:    Oro\Bundle\FormBundle\Form\Type\OroComboboxLocalType
    oro_form.type.entity_identifier.class: Oro\Bundle\FormBundle\Form\Type\EntityIdentifierType
    oro_form.type.jqueryselect2_hidden.class: Oro\Bundle\FormBundle\Form\Type\OroJquerySelect2HiddenType

services:
    # Form types
    oro_form.type.date:
        class: %oro_form.type.date.class%
        tags:
            - { name: form.type, alias: oro_date }

    oro_form.type.datetime:
        class: %oro_form.type.datetime.class%
        tags:
            - { name: form.type, alias: oro_datetime }

    oro_form.type.jqueryselect2_hidden:
        class: %oro_form.type.jqueryselect2_hidden.class%
        arguments:
            - @oro_form.autocomplete.transformer.entity_to_text
            - @doctrine.orm.entity_manager
            - @oro_form.autocomplete.configuration
        tags:
            - { name: form.type, alias: oro_jqueryselect2_hidden }

    oro_form.type.entity_identifier:
        class: %oro_form.type.entity_identifier.class%
        tags:
            - { name: form.type, alias: oro_entity_identifier }
        arguments: ["@doctrine"]
