parameters:
    oro_form.type.date.class:                 Oro\Bundle\FormBundle\Form\Type\OroDateType
    oro_form.type.datetime.class:             Oro\Bundle\FormBundle\Form\Type\OroDateTimeType
    oro_form.type.combobox_local.class:       Oro\Bundle\FormBundle\Form\Type\OroComboboxLocalType
    oro_form.type.entity_identifier.class:    Oro\Bundle\FormBundle\Form\Type\EntityIdentifierType
    oro_form.type.jqueryselect2_hidden.class: Oro\Bundle\FormBundle\Form\Type\OroJquerySelect2HiddenType
    oro_form.type.translatable_entity.class:  Oro\Bundle\FormBundle\Form\Type\TranslatableEntityType

services:
    # Form types
    oro_form.type.date:
        class: %oro_form.type.date.class%
        tags:
            - { name: form.type, alias: oro_date }

    oro_form.type.datetime:
        class: %oro_form.type.datetime.class%
        tags:
            - { name: form.type, alias: oro_datetime }

    oro_form.type.entity_identifier:
        class: %oro_form.type.entity_identifier.class%
        arguments: ["@doctrine"]
        tags:
            - { name: form.type, alias: oro_entity_identifier }

    oro_form.type.jqueryselect2_hidden:
        class: %oro_form.type.jqueryselect2_hidden.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_form.autocomplete.search_registry
        tags:
            - { name: form.type, alias: oro_jqueryselect2_hidden }

    oro_form.type.translatable_entity:
        class: %oro_form.type.translatable_entity.class%
        arguments: ["@doctrine"]
        tags:
            - { name: form.type, alias: translatable_entity }

    oro_form.type.jqueryselect2_translatable_entity:
        parent: genemu.form.jquery.type.select2
        arguments: ["translatable_entity"]
        tags:
            - { name: form.type, alias: genemu_jqueryselect2_translatable_entity }
