parameters:
    oro_form.type.date.class:                       Oro\Bundle\FormBundle\Form\Type\OroDateType
    oro_form.type.datetime.class:                   Oro\Bundle\FormBundle\Form\Type\OroDateTimeType
    oro_form.type.money.class:                      Oro\Bundle\FormBundle\Form\Type\OroMoneyType
    oro_form.type.entity_identifier.class:          Oro\Bundle\FormBundle\Form\Type\EntityIdentifierType
    oro_form.type.jqueryselect2_hidden.class:       Oro\Bundle\FormBundle\Form\Type\OroJquerySelect2HiddenType
    oro_form.extension.data_block.class:            Oro\Bundle\FormBundle\Form\Extension\DataBlockExtension
    oro_form.extension.client_validation.class:     Oro\Bundle\FormBundle\Form\Extension\ClientValidationExtension
    oro_form.type.icon.class:                       Oro\Bundle\FormBundle\Form\Type\OroIconType
    oro_form.type.multiple_entity.class:            Oro\Bundle\FormBundle\Form\Type\MultipleEntityType
    oro_form.extension.tooltip.class:               Oro\Bundle\FormBundle\Form\Extension\TooltipFormExtension

services:
    # Form types
    oro_form.type.date:
        class: %oro_form.type.date.class%
        arguments:
            - @translator
            - @oro_locale.format_converter.date_time.registry
        tags:
            - { name: form.type, alias: oro_date }

    oro_form.type.datetime:
        class: %oro_form.type.datetime.class%
        arguments:
            - @translator
            - @oro_locale.settings
            - @oro_locale.format_converter.date_time.registry
        tags:
            - { name: form.type, alias: oro_datetime }

    oro_form.type.money:
        class: %oro_form.type.money.class%
        arguments:
            - @oro_locale.settings
        tags:
            - { name: form.type, alias: oro_money }

    oro_form.type.icon:
        class: %oro_form.type.icon.class%
        tags:
            - { name: form.type, alias: oro_icon_select }

    oro_form.type.entity_identifier:
        class: %oro_form.type.entity_identifier.class%
        arguments: ["@doctrine"]
        tags:
            - { name: form.type, alias: oro_entity_identifier }

    oro_form.type.jqueryselect2_hidden:
        class: %oro_form.type.jqueryselect2_hidden.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_form.autocomplete.search_registry
        tags:
            - { name: form.type, alias: oro_jqueryselect2_hidden }

    oro_form.extension.data_block:
        class: %oro_form.extension.data_block.class%
        tags:
            - { name: form.type_extension, alias: form }

    oro_form.extension.client_validation:
        class: %oro_form.extension.client_validation.class%
        tags:
            - { name: form.type_extension, alias: form }

    oro_form.type.multiple_entity:
        class: %oro_form.type.multiple_entity.class%
        tags:
            - { name: form.type, alias: oro_multiple_entity }

    oro_help.form.tooltip_extension:
        class: %oro_form.extension.tooltip.class%
        tags:
            - {name: form.type_extension, alias: form }
