config:
    paths:
        'oro/select2-config': 'bundles/oroform/js/select2-config.js'
        'oro/multiple-entity': 'bundles/oroform/js/multiple-entity.js'
        'oro/multiple-entity/view': 'bundles/oroform/js/multiple-entity/view.js'
        'oro/multiple-entity/model': 'bundles/oroform/js/multiple-entity/model.js'
        'oro/multiple-entity/collection': 'bundles/oroform/js/multiple-entity/collection.js'