config:
    shim:
        'jquery.validate':
            deps:
                - 'jquery'
        'tinymce/plugins/textcolor/plugin.min':
            deps:
                - 'tinymce/tinymce.min'
        'tinymce/plugins/code/plugin.min':
            deps:
                - 'tinymce/tinymce.min'
        'tinymce/plugins/link/plugin.min':
            deps:
                - 'tinymce/tinymce.min'
        'tinymce/themes/modern/theme.min':
            deps:
                - 'tinymce/tinymce.min'
        'tinymce/jquery.tinymce.min':
            deps:
                - 'jquery'
                - 'tinymce/tinymce.min'
                - 'tinymce/plugins/textcolor/plugin.min'
                - 'tinymce/plugins/code/plugin.min'
                - 'tinymce/plugins/link/plugin.min'
                - 'tinymce/themes/modern/theme.min'
            exports: 'jQuery'
    map:
        '*':
            'jquery.validate': 'oroform/js/extend/validate'
        'oroform/js/extend/validate':
            'jquery.validate': 'jquery.validate'
    paths:
        'oroform/lib/jquery.timepicker-1.4.13/jquery.timepicker': 'bundles/oroform/lib/jquery.timepicker-1.4.13/jquery.timepicker.min.js'
        'jquery.validate': 'bundles/oroform/lib/jquery.validate/jquery.validate.js'
        'oroform/js/validator/count': 'bundles/oroform/js/validator/count.js'
        'oroform/js/validator/date': 'bundles/oroform/js/validator/date.js'
        'oroform/js/validator/datetime': 'bundles/oroform/js/validator/datetime.js'
        'oroform/js/validator/email': 'bundles/oroform/js/validator/email.js'
        'oroform/js/validator/length': 'bundles/oroform/js/validator/length.js'
        'oroform/js/validator/notblank': 'bundles/oroform/js/validator/notblank.js'
        'oroform/js/validator/notnull': 'bundles/oroform/js/validator/notnull.js'
        'oroform/js/validator/number': 'bundles/oroform/js/validator/number.js'
        'oroform/js/validator/range': 'bundles/oroform/js/validator/range.js'
        'oroform/js/validator/regex': 'bundles/oroform/js/validator/regex.js'
        'oroform/js/validator/repeated': 'bundles/oroform/js/validator/repeated.js'
        'oroform/js/validator/time': 'bundles/oroform/js/validator/time.js'
        'oroform/js/validator/url': 'bundles/oroform/js/validator/url.js'

        'oroform/js/formatter/field': 'bundles/oroform/js/formatter/field.js'

        'oroform/js/select2-config': 'bundles/oroform/js/select2-config.js'
        'oroform/js/multiple-entity': 'bundles/oroform/js/multiple-entity.js'
        'oroform/js/multiple-entity/view': 'bundles/oroform/js/multiple-entity/view.js'
        'oroform/js/multiple-entity/model': 'bundles/oroform/js/multiple-entity/model.js'
        'oroform/js/multiple-entity/collection': 'bundles/oroform/js/multiple-entity/collection.js'
        'oroform/js/select2_relevancy_order_handler': 'bundles/oroform/js/select2-relevancy-order-handler.js'
        'oroform/js/create-select-type-handler': 'bundles/oroform/js/create-select-type-handler.js'
        'oroform/js/select-create-inline-type-handler': 'bundles/oroform/js/select-create-inline-type-handler.js'

        'oroform/js/optional-validation-handler': 'bundles/oroform/js/optional-validation-handler.js'

        'oroform/js/app/views/datepicker/datetimepicker-view': 'bundles/oroform/js/app/views/datepicker/datetimepicker-view.js'
        'oroform/js/app/views/datepicker/datepicker-view': 'bundles/oroform/js/app/views/datepicker/datepicker-view.js'
        'oroform/js/app/views/wysiwig-editor/wysiwyg-editor-view': 'bundles/oroform/js/app/views/wysiwig-editor/wysiwyg-editor-view.js'
        'oroform/js/app/views/simple-color-picker-view': 'bundles/oroform/js/app/views/simple-color-picker-view.js'
        'oroform/js/app/views/simple-color-choice-view': 'bundles/oroform/js/app/views/simple-color-choice-view.js'
        'oroform/js/app/views/color-table-view': 'bundles/oroform/js/app/views/color-table-view.js'
build:
    paths:
        'tinymce/tinymce.min': 'empty:'
        'tinymce/tinymce.jquery.min': 'empty:'
        'tinymce/plugins/textcolor/plugin.min': 'empty:'
        'tinymce/plugins/code/plugin.min': 'empty:'
        'tinymce/plugins/link/plugin.min': 'empty:'
        'tinymce/themes/modern/theme.min': 'empty:'
        'oroform/lib/jquery.timepicker-1.4.13/jquery.timepicker': 'empty:'
