parameters:
    oro_form.twig.form.class:                     Oro\Bundle\FormBundle\Twig\FormExtension
    oro_form.autocomplete.config.handler.class:   Oro\Bundle\FormBundle\Autocomplete\ConfigHandler

services:
    oro_form.twig.form_extension:
        class: %oro_form.twig.form.class%
        tags:
            - { name: twig.extension }