parameters:
    oro_form.validator.constraint_factory.class:               Oro\Bundle\FormBundle\Validator\ConstraintFactory
    oro_form.js_validation.constraints_provider.class:         Oro\Bundle\FormBundle\JsValidation\ConstraintsProvider
    oro_form.twig.js_validation_extension.class:               Oro\Bundle\FormBundle\Twig\JsValidationExtension
    oro_form.twig.form.class:                                  Oro\Bundle\FormBundle\Twig\FormExtension

services:
    oro_form.validator.constraint_factory:
        class: %oro_form.validator.constraint_factory.class%

    oro_form.js_validation.constraints_provider:
        class: %oro_form.js_validation.constraints_provider.class%
        arguments:
            - @validator.mapping.class_metadata_factory

    oro_form.twig.js_validation_extension:
        class: %oro_form.twig.js_validation_extension.class%
        tags:
            - { name: twig.extension }
