parameters:
    oro_form.validator.constraint_factory.class: Oro\Bundle\FormBundle\Validator\ConstraintFactory
    oro_form.twig.form.class:                    Oro\Bundle\FormBundle\Twig\FormExtension
    oro_form.twig.js_validation_extension.class: Oro\Bundle\FormBundle\Twig\JsValidationExtension
    oro_form.guesser.chain.class:                Oro\Bundle\FormBundle\Guesser\ChainFormGuesser

services:
    oro_form.validator.constraint_factory:
        class: %oro_form.validator.constraint_factory.class%

    oro_form.twig.form_extension:
        class: %oro_form.twig.form.class%
        tags:
            - { name: twig.extension }

    oro_form.twig.js_validation_extension:
        class: %oro_form.twig.js_validation_extension.class%
        tags:
            - { name: twig.extension }

    oro_form.guesser.chain:
        class: %oro_form.guesser.chain.class%
