styles:
    inputs:
        - 'bundles/oroform/blank/scss/variables/settings.scss'
        - 'bundles/oroform/blank/scss/variables/button-config.scss'
        - 'bundles/oroform/blank/scss/variables/custom-checkbox-config.scss'
        - 'bundles/oroform/blank/scss/variables/input-config.scss'
        - 'bundles/oroform/blank/scss/variables/select-config.scss'
        - 'bundles/oroform/blank/scss/styles.scss'
    filters: ['cssrewrite', 'cssmin']
